In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
import urllib3
http = urllib3.PoolManager()
r = http.request('GET', 
"https://raw.githubusercontent.com/dwyl/english-words/master/words.txt", 
preload_content=False)
with open("desktop/data science/python/data/words.txt", 'wb') as out:
    data = r.read()
    out.write(data)
r.release_conn()

/Users/jyotikhetan/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)


4863005

In [4]:
word_list=open("desktop/data science/python/data/words.txt").readlines()
word_list=map(str.strip,word_list)

In [5]:
word_list=[word for word in word_list if len(word)==3]
word_list=[word for word in word_list if word[0].islower()]
word_list=[word for word in word_list if word.isalpha()]
word_list=list(map(str.lower,word_list))
print(word_list)
#word_list.sort()
#print(word_list)
len(word_list)

['aah', 'aal', 'abb', 'abd', 'aby', 'abl', 'abn', 'abr', 'abt', 'abv', 'acy', 'ade', 'ady', 'adj', 'ado', 'adv', 'adz', 'aeq', 'aer', 'afd', 'aff', 'aga', 'age', 'agy', 'ago', 'ahi', 'aho', 'ahs', 'ahu', 'aye', 'aik', 'ail', 'ays', 'ait', 'ayu', 'ake', 'ako', 'aku', 'ale', 'aly', 'alk', 'all', 'aln', 'alt', 'alw', 'ana', 'and', 'ane', 'ans', 'ant', 'aob', 'aor', 'aph', 'apx', 'arb', 'ard', 'ary', 'arn', 'arr', 'art', 'arx', 'asb', 'ase', 'ast', 'ate', 'aud', 'auf', 'auh', 'aul', 'avg', 'avn', 'awa', 'awd', 'awe', 'awm', 'awn', 'azo', 'bad', 'bah', 'baw', 'bbs', 'bcf', 'bdl', 'bec', 'beg', 'bey', 'bet', 'bhd', 'bye', 'big', 'bin', 'bio', 'byp', 'bys', 'biz', 'bkg', 'bks', 'bkt', 'bld', 'ble', 'blk', 'blo', 'boa', 'boe', 'bog', 'boh', 'boo', 'bpt', 'brr', 'bsh', 'buy', 'bun', 'buz', 'bvt', 'bxs', 'cag', 'cay', 'caw', 'ccm', 'cdg', 'cee', 'cep', 'cfh', 'cfm', 'cfs', 'chg', 'chn', 'chs', 'cyc', 'cig', 'cyl', 'cyp', 'cir', 'civ', 'ckw', 'cle', 'clk', 'cog', 'cow', 'coz', 'cre', 'cro', 'cru'

1018

In [6]:
import numpy as np
word_list=np.asarray(word_list)
word_list.dtype
word_list.sort()
word_list

dtype('<U3')

array(['aah', 'aal', 'abb', ..., 'zod', 'zoo', 'zzt'], dtype='<U3')

In [7]:
word_bytes=np.ndarray((word_list.size,word_list.itemsize),dtype='uint8',buffer=word_list.data)
word_bytes
word_bytes[0]
word_bytes.shape
word_bytes=word_bytes[:,::word_list.itemsize//3]
word_bytes
word_bytes.shape

array([[ 97,   0,   0, ...,   0,   0,   0],
       [ 97,   0,   0, ...,   0,   0,   0],
       [ 97,   0,   0, ...,   0,   0,   0],
       ...,
       [122,   0,   0, ...,   0,   0,   0],
       [122,   0,   0, ...,   0,   0,   0],
       [122,   0,   0, ...,   0,   0,   0]], dtype=uint8)

array([ 97,   0,   0,   0,  97,   0,   0,   0, 104,   0,   0,   0],
      dtype=uint8)

(1018, 12)

array([[ 97,  97, 104],
       [ 97,  97, 108],
       [ 97,  98,  98],
       ...,
       [122, 111, 100],
       [122, 111, 111],
       [122, 122, 116]], dtype=uint8)

(1018, 3)

In [8]:
word_list[0:5]
word_bytes[0:5]

array(['aah', 'aal', 'abb', 'abd', 'abl'], dtype='<U3')

array([[ 97,  97, 104],
       [ 97,  97, 108],
       [ 97,  98,  98],
       [ 97,  98, 100],
       [ 97,  98, 108]], dtype=uint8)

In [9]:
from scipy.spatial.distance import pdist,squareform
from scipy.sparse import csr_matrix
import numpy as np
hamming_dist=pdist(word_bytes,metric='hamming')
hamming_dist.shape
hamming_dist

(517653,)

array([0.33333333, 0.66666667, 0.66666667, ..., 0.33333333, 0.66666667,
       0.66666667])

In [10]:
word_list[0:4]
word_bytes[0:4]
hamming_dist[0:4]

array(['aah', 'aal', 'abb', 'abd'], dtype='<U3')

array([[ 97,  97, 104],
       [ 97,  97, 108],
       [ 97,  98,  98],
       [ 97,  98, 100]], dtype=uint8)

array([0.33333333, 0.66666667, 0.66666667, 0.66666667])

In [11]:
squareform(hamming_dist)
squareform(hamming_dist)[0:4,0:4]
mat=squareform(hamming_dist<1.5/3)
mat.shape
mat[0:4,0:4]

array([[0.        , 0.33333333, 0.66666667, ..., 1.        , 1.        ,
        1.        ],
       [0.33333333, 0.        , 0.66666667, ..., 1.        , 1.        ,
        1.        ],
       [0.66666667, 0.66666667, 0.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [1.        , 1.        , 1.        , ..., 0.        , 0.33333333,
        0.66666667],
       [1.        , 1.        , 1.        , ..., 0.33333333, 0.        ,
        0.66666667],
       [1.        , 1.        , 1.        , ..., 0.66666667, 0.66666667,
        0.        ]])

array([[0.        , 0.33333333, 0.66666667, 0.66666667],
       [0.33333333, 0.        , 0.66666667, 0.66666667],
       [0.66666667, 0.66666667, 0.        , 0.33333333],
       [0.66666667, 0.66666667, 0.33333333, 0.        ]])

(1018, 1018)

array([[False,  True, False, False],
       [ True, False, False, False],
       [False, False, False,  True],
       [False, False,  True, False]])

In [12]:
graph=csr_matrix(mat)
mat[0:6,0:64]
print(graph[0:3])

array([[False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False,
        False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, Fals

  (0, 1)	True
  (0, 49)	True
  (0, 64)	True
  (0, 78)	True
  (0, 159)	True
  (0, 328)	True
  (0, 415)	True
  (0, 471)	True
  (0, 625)	True
  (0, 700)	True
  (0, 740)	True
  (0, 912)	True
  (0, 965)	True
  (1, 0)	True
  (1, 4)	True
  (1, 30)	True
  (1, 37)	True
  (1, 65)	True
  (1, 371)	True
  (2, 3)	True
  (2, 4)	True
  (2, 5)	True
  (2, 6)	True
  (2, 7)	True
  (2, 8)	True
  (2, 9)	True
  (2, 47)	True
  (2, 51)	True
  (2, 58)	True
  (2, 199)	True
  (2, 566)	True


In [13]:
i1= word_list.searchsorted ('and')
i2= word_list.searchsorted ('dog')
word_list[i1]
word_list[i2]

'and'

'dog'

In [14]:
from scipy.sparse.csgraph import dijkstra
distance,predecessors=dijkstra(graph,indices=i1,return_predecessors=True)
i1
i2
word_list[43]
word_list[44]
distance[0:20]
predecessors[0:20]
distance[i2]

43

176

'and'

'ane'

array([3., 3., 2., 1., 2., 2., 2., 2., 2., 2., 3., 2., 3., 3., 3., 3., 3.,
       4., 3., 1.])

array([64, 65,  3, 43,  3,  3,  3,  3,  3,  3,  9, 44, 11, 11,  8,  9, 11,
       18, 54, 43], dtype=int32)

5.0

In [15]:
path=[]
i=i2
while i!=i1:
    path.append(word_list[i])
    i=predecessors[i]
    word_list[i]
path.append(word_list[i1])
path
path[::-1]

'dug'

'mug'

'mud'

'aud'

'and'

['dog', 'dug', 'mug', 'mud', 'aud', 'and']

['and', 'aud', 'mud', 'mug', 'dug', 'dog']

In [16]:
#not connected with any word in list
from scipy.sparse.csgraph import connected_components
N_components,component_list=connected_components(graph)
N_components
component_list.shape
component_list[0:90]
word_list[81]
word_list[82]

9

(1018,)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0,
       0, 0], dtype=int32)

'bcf'

'bdl'

In [17]:
[np.sum(component_list==i) for i in range(N_components)]

[1010, 1, 1, 1, 1, 1, 1, 1, 1]

In [18]:
[list(word_list[np.where(component_list==i)])for i in range(1,N_components)]

[['bcf'], ['bdl'], ['epi'], ['mmf'], ['sml'], ['wjc'], ['xcl'], ['xyz']]

In [19]:
#maximum distance words
distance,predecessors=dijkstra(graph,return_predecessors=True)
max_distance=np.max(distance[~np.isinf(distance)])
max_distance
distance[0:9,0:9]
predecessors[0:9,0:9]
word_list[0:9]

11.0

array([[0., 1., 3., 3., 2., 3., 3., 3., 3.],
       [1., 0., 2., 2., 1., 2., 2., 2., 2.],
       [3., 2., 0., 1., 1., 1., 1., 1., 1.],
       [3., 2., 1., 0., 1., 1., 1., 1., 1.],
       [2., 1., 1., 1., 0., 1., 1., 1., 1.],
       [3., 2., 1., 1., 1., 0., 1., 1., 1.],
       [3., 2., 1., 1., 1., 1., 0., 1., 1.],
       [3., 2., 1., 1., 1., 1., 1., 0., 1.],
       [3., 2., 1., 1., 1., 1., 1., 1., 0.]])

array([[-9999,     0,     4,    62,     1,     4,     4,     4,     4],
       [    1, -9999,     4,     4,     1,     4,     4,     4,     4],
       [    1,     4, -9999,     2,     2,     2,     2,     2,     2],
       [   64,     4,     3, -9999,     3,     3,     3,     3,     3],
       [    1,     4,     4,     4, -9999,     4,     4,     4,     4],
       [    1,     4,     5,     5,     5, -9999,     5,     5,     5],
       [    1,     4,     6,     6,     6,     6, -9999,     6,     6],
       [    1,     4,     7,     7,     7,     7,     7, -9999,     7],
       [    1,     4,     8,     8,     8,     8,     8,     8, -9999]],
      dtype=int32)

array(['aah', 'aal', 'abb', 'abd', 'abl', 'abn', 'abr', 'abt', 'abv'],
      dtype='<U3')

In [20]:
i1,i2=np.where(distance==max_distance)
list(zip(word_list[i1],word_list[i2]))

[('dlr', 'hmm'),
 ('dlr', 'kmc'),
 ('hmm', 'dlr'),
 ('hmm', 'lbf'),
 ('hmm', 'rfz'),
 ('hmm', 'tfr'),
 ('kmc', 'dlr'),
 ('kmc', 'tfr'),
 ('lbf', 'hmm'),
 ('rfz', 'hmm'),
 ('tfr', 'hmm'),
 ('tfr', 'kmc')]

In [23]:
for j,i in zip(i1,i2):
    path = []
    while i != j:
        path.append(word_list[i])
        i = predecessors[j,i]
    path.append(word_list[j])
    print(path[::-1])

['dlr', 'tlr', 'tlo', 'blo', 'boo', 'boh', 'bsh', 'ush', 'usu', 'umu', 'umm', 'hmm']
['dlr', 'tlr', 'tlo', 'blo', 'bld', 'bad', 'bah', 'pah', 'pph', 'kph', 'kpc', 'kmc']
['hmm', 'umm', 'umu', 'usu', 'ust', 'ugt', 'tgt', 'tot', 'too', 'tlo', 'tlr', 'dlr']
['hmm', 'umm', 'umu', 'usu', 'ust', 'ast', 'abt', 'abv', 'dbv', 'dbw', 'lbw', 'lbf']
['hmm', 'umm', 'ump', 'unp', 'uns', 'ons', 'ous', 'ouf', 'suf', 'suz', 'sfz', 'rfz']
['hmm', 'umm', 'umu', 'usu', 'ust', 'ugt', 'tgt', 'tot', 'too', 'tlo', 'tlr', 'tfr']
['kmc', 'kpc', 'kph', 'iph', 'ich', 'ick', 'ilk', 'blk', 'blo', 'tlo', 'tlr', 'dlr']
['kmc', 'kpc', 'kph', 'iph', 'ich', 'ick', 'ilk', 'blk', 'blo', 'tlo', 'tlr', 'tfr']
['lbf', 'lbw', 'dbw', 'daw', 'baw', 'bah', 'bsh', 'ush', 'usu', 'umu', 'umm', 'hmm']
['rfz', 'rfb', 'rhb', 'rho', 'sho', 'shi', 'ihi', 'imi', 'imu', 'umu', 'umm', 'hmm']
['tfr', 'tlr', 'tlo', 'blo', 'boo', 'boh', 'bsh', 'ush', 'usu', 'umu', 'umm', 'hmm']
['tfr', 'tlr', 'tlo', 'blo', 'bld', 'bad', 'bah', 'pah', 'pph', '